### ISSUE TITLE
Changing chat message sending from full-page submission to Ajax and improving chatting experience

### ISSUE THREAD

**Issue by TundeMichael** [numahealth/Asknuma#19]
The chatting between the platform users and the Administrator is currently a full page submission. That is when a user sends a chat message, the whole page is reloaded and one has to scroll down again to find the chat message box etc. This gives a poor user experience especially the scrolling part.

**Comment by tobiobisanya** [comment]
How do we change this?

**Comment by TundeMichael** [comment]
@tobiobisanya This issue has been solved to a large extent (there is still room for improvement). The chatting and image uploads on both the Admin and User chatting ends are now Ajax submission. To test, login as Admin as well as a User and try out the chatting. To compare the way it was before, you can login to the formal version and also try out the chat.

**Comment by tobiobisanya** [comment]
Is this new set-up still compatible with the messages coming through to the Numa Slack? because I just sent a message as a user & it did not come through to Slack @TundeMichael. this is currently the only way we know to be alerted that someone has asked a question & we need to react to it. because the Admin back end is quite unhelfpul from that regard. So we really need the Slack to work.

Otherwise I think your tweaks work very well!

**Comment by TundeMichael** [comment]
@tobiobisanya  The issue had to do with slack token used by Unyscape been disabled. I have created another one and everything works fine now.
